name: GitHub CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  PYEDB_USE_DOTNET: '1'
  PYEDB_CI_NO_DISPLAY: '1'
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: 'pyedb'
  DOCUMENTATION_CNAME: 'edb.docs.pyansys.com'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_HOST_URL: ${{ vars.MEILISEARCH_HOST_URL }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-pyaedt-main-windows:
    name: Testing PyAEDT main branch (Windows)
    runs-on: [ self-hosted, Windows, pyaedt ]
    steps:
      - name: Install Git and checkout project
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create Python venv
        run: |
          python -m venv .venv
          . .venv\Scripts\Activate.ps1

      - name: Update pip
        run: |
          . .venv\Scripts\Activate.ps1
          python -m pip install -U pip

      - name: Clone PyAEDT on main branch
        uses: actions/checkout@v4
        with:
          repository: ansys/pyaedt
          path: "external/pyaedt"
          ref: "main"

      - name: Install PyAEDT main branch version with its test dependencies
        run: |
          . .venv\Scripts\Activate.ps1
          pip install --no-cache-dir external/pyaedt[tests]

      - name: Install PyEDB
        run: |
          . .venv\Scripts\Activate.ps1
          python -m pip install .

      - name: Install CI dependencies (e.g. vtk-osmesa)
        run: |
          .venv\Scripts\Activate.ps1
          # Uninstall conflicting dependencies
          pip uninstall --yes vtk
          pip install --extra-index-url https://wheels.vtk.org vtk-osmesa

      - name: Run PyAEDT tests
        uses: nick-fields/retry@v3
        env:
          PYTHONMALLOC: malloc
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 40
          command: |
            .venv\Scripts\Activate.ps1
            pytest -n auto --dist loadfile --durations=50 -v external/pyaedt/tests/system/general/
